### ISSUE TITLE
Implement registration page

### ISSUE THREAD

**Issue by revanthraghu** [revanthraghu/Expense-Manager#1]
### Axios request 
```javascript
axios({
method: "post", 
url: "http://localhost:5000/api/register", 
headers: {"content-type": "application/json"}, 
data: {name: <firstname + lastname>, email, password}
})
```

- [x] Frontend

- [x] Backend

**Comment by revanthraghu** [comment]
@AkhilaG28 Check this out, added 2 issues and linked them to a milestone, created a kanban board in projects, every new issue will be added to the to-do board automatically when issue is linked to Expense Manager project on the right of issue page.

**Comment by AkhilaG28** [comment]
Created Registration Page
